### ISSUE TITLE
请问是否打算公开ASUKA的代码

### ISSUE THREAD

**Issue by lawsonxwl** [ewrfcas/ewrfcas.github.io#1]
尝试在diffusers库上沿用部分mae-far的代码进行了asuka的复现，发现模型大多情况下不能够很好的跟随mae prior，而是在mask区域生成失真的内容，asuka是基于ldm的库训练的还是基于diffusers？能否帮忙回答一下~

**Comment by ewrfcas** [comment]
由于一些项目限制，我们短期内还没有开源计划。
